resources:
- oil-stories-deploy.yaml
- console.yaml

patches:
  - patch: |-
      - op: add
        path: "/spec/plugins"
        value:
          - oil-stories-plugin
    target:
      group: operator.openshift.io
      kind: Console
      version: v1
      name: cluster
